spring:
  application:
    name: sampleexchangeconvert
  config:
    import: optional:file:.env[.properties]
  jackson:
    serialization:
      fail-on-empty-beans: false
    time-zone: Europe/Istanbul

exchange-api:
  api-url: https://api.apilayer.com
  api-key: ivOUu1QhVplJYUNXDXVuxyJHMcglvuya
  api-call-limit: 60
  cache-name: exchanges
  cache-ttl: 10000 # 10 seconds


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true

server:
  port: 1331